FROM postgres:18

# Configuración de zona horaria (Chile)
ENV TZ="America/Santiago"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Scripts de inicialización (orden alfabético)
COPY ./init-scripts/01-init_schema.sql /docker-entrypoint-initdb.d/01-init_schema.sql
COPY ./init-scripts/02-seed_test_data.sql /docker-entrypoint-initdb.d/02-seed_test_data.sql

EXPOSE 5432
