FROM postgres:18

# Configuración de zona horaria
ENV TZ="America/Santiago"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Scripts de inicialización (se ejecutan en orden alfabético)
COPY ./init-scripts/01-users.sql /docker-entrypoint-initdb.d/01-users.sql
COPY ./init-scripts/02-schema-stg.sql /docker-entrypoint-initdb.d/02-schema-stg.sql
COPY ./init-scripts/03-schema-dwh.sql /docker-entrypoint-initdb.d/03-schema-dwh.sql
# Incluir datos de prueba solo en testing
COPY ./init-scripts/04-seed-test-data.sql /docker-entrypoint-initdb.d/04-seed-test-data.sql

EXPOSE 5432
